Improvement in RipUtils
4pr0n/ripme pull request #544
Opened 2017-05-18 04:38 UTC by Gaboso

Defined a constant instead of duplicating this literal "imgur.com".
Defined a constant instead of duplicating this literal "http: //".
Moved strings to the left side of the string comparison.
Added a private constructor to hide the implicit public one.
Removed redundant initializers.
Changed indexOf(char) to single quotes for optimized for single characters.
Removed commented code blocks.
In the urlFromDirectoryName method, the first 'if' is always null, so I removed it.
Changed constant logger name to LOGGER.
Replace usage of System.out by Logger.

2017-05-18 11:53 UTC, rautamiekka commented
While it's not 100% necessary, escaping the dots in website addresses in a RegEx ensures 100% success and is a performance optimization.

Also, just in case a site switches from HTTP to HTTPS or the other way around later a constant should be defined (instead of hardcoding in the code) and used like this (imitated from the very code) in Imgur's case:
```java
private static final String SITE_PROTOCOL = "http";
private static final String SITE_ADDRESS = SITE_PROTOCOL + "://imgur.com";

some_code(SITE_ADDRESS + "/01.png");
```

2017-05-18 17:13 UTC, metaprime requested changes

2017-05-18 17:13 UTC, metaprime commented on src/main/java/com/rarchives/ripme/utils/RipUtils.java
> +        LOGGER.debug("Checking " + url);
Lowercase logger is used throughout ripme. Sure it's a convention for "constants" to be in all caps, but that static final variable isn't even benefitting from pretending to be a constant. Sure you can't reassign it, but as an output logger, it's state changes. I don't think anything useful is documented there. I'd prefer keeping it lowercase `logger` for consistency with the rest of the program and to reduce the size of unnecessary diffs. If you're serious about this change, it needs to change in the whole project.

2017-05-18 17:13 UTC, metaprime commented on src/main/java/com/rarchives/ripme/utils/RipUtils.java
> +import org.jsoup.nodes.Element;
Just wondering for future consistency, what tool or scheme did you use to sort the imports?

2017-05-18 17:13 UTC, metaprime commented on src/main/java/com/rarchives/ripme/utils/RipUtils.java
> +        if ((url.getHost().endsWith(IMGUR_COM)) && url.toExternalForm().contains("imgur.com/a/")) {
Not going to replace the `imgur.com` at the end of this line?

2017-05-18 17:13 UTC, metaprime commented on src/main/java/com/rarchives/ripme/utils/RipUtils.java
> +        if (url.getHost().equals(IMGUR_COM) || "m.imgur.com".equals(url.getHost())) {
make a constant for M_IMGUR_COM

2017-05-18 17:13 UTC, metaprime commented on src/main/java/com/rarchives/ripme/utils/RipUtils.java
> +            url = urlFromImagefapDirectoryName(dir);
So this whole thing, as a style guideline one of three things can happen. `if` statement with a single statement body all on a single line (as it was before), the same with braces around the body (my preference), or indented WITH braces added around the body.

Absolutely please do not use the indented form without adding brackets.

IMO, the single-line forms are more readable in this case.

If you want to make a change here, please add brackets around the if bodies and it's up to you whether to reformat so the bodies are all on their own lines.

Also looking at this code now, I feel like there's got to be a better way of writing this bit of code (more efficient, etc.). If you make that sort of change, please do it is in a separate commit or pull request.

2017-05-18 17:13 UTC, metaprime commented on src/main/java/com/rarchives/ripme/utils/RipUtils.java
> -        }
Don't remove braces around if or loop bodies. They should be required AFAIC.

2017-05-18 17:13 UTC, metaprime commented on src/main/java/com/rarchives/ripme/utils/RipUtils.java
> -        }
Keep braces.

2017-05-18 17:13 UTC, metaprime commented on src/main/java/com/rarchives/ripme/utils/RipUtils.java
> +            url = "http://www.imagefap.com/gallery.php?pgid=" + directory;
Please keep braces.

2017-05-18 18:16 UTC, Gaboso commented on src/main/java/com/rarchives/ripme/utils/RipUtils.java
> +import org.jsoup.nodes.Element;
I'm using IntelliJ IDEA

2017-08-25 19:14 UTC, closed without merging

2017-09-02 07:30 UTC, metaprime commented
@Gaboso Why did you close the PR? Apologies for not following up on this.